lenguage: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mitre90/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mitre90/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-078764109390"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"